---
#                         _           __      _       __     ___            _        
#   __ _ _ __   __ _  ___| |__   ___ / /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
#  / _` | '_ \ / _` |/ __| '_ \ / _ \ || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | (_| | |_) | (_| | (__| | | |  __/ || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
#  \__,_| .__/ \__,_|\___|_| |_|\___| || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
#       |_|                          \_\_|        |___/_/                            
# install-pkg
- block:
    - name: install-pkg | RedHat | Apache should be installed
      yum:
        name:  "httpd"
        state: "present"

    - name: install-pkg | RedHat | Apache related packages should be installed
      yum:
        state: "present"
        name:
          - "apr"
          - "apr-util"
          - "httpd-devel"
          - "httpd-tools"
          - "apachetop"
          - "munin-apache"
          - "mod_ssl"

    - name: install-pkg | RedHat | HTTP related packages should be installed
      yum:
        state: "present"
        name:
          - "curl"
          - "wget"
          - "cronolog"
  when: ansible_os_family == "RedHat"

