---
#                         _           __      _       __     ___            _        
#   __ _ _ __   __ _  ___| |__   ___ / /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
#  / _` | '_ \ / _` |/ __| '_ \ / _ \ || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | (_| | |_) | (_| | (__| | | |  __/ || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
#  \__,_| .__/ \__,_|\___|_| |_|\___| || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
#       |_|                          \_\_|        |___/_/                            
# make-config
- block:
  - name: make-config | RedHat | Deploy each config file in /etc/httpd/conf
    notify: Restart Apache
    template:
      src:  "etc/httpd/conf/{{ item }}.j2"
      dest: "{{ apache.configroot }}/{{ item }}"
      mode: "0644"
    with_items:
      - "httpd.conf"
  
  - name: make-config | RedHat | Deploy each config file in /etc/httpd/conf.d
    notify: Restart Apache
    template:
      src:  "{{ item }}"
      dest: "{{ apache.serverroot }}/conf.d/{{ item | basename | replace('.j2', '') }}"
      mode: "0644"
    with_fileglob: "templates{{ apache.serverroot }}/conf.d/*.conf.j2"
  
  - name: make-config | RedHat | /etc/httpd/conf.vhosts.d should be exist
    file:
      path:   "{{ apache.serverroot }}/conf.vhosts.d"
      state:  "directory"
      owner:  "root"
      group:  "root"
      mode:   "0755"
  
  - name: make-config | RedHat | /etc/httpd/ssl should be exist
    file:
      path:   "{{ apache.serverroot }}/ssl"
      state:  "directory"
      owner:  "root"
      group:  "root"
      mode:   "0755"
  
  - name: make-config | RedHat | Deploy each file in /etc/httpd/conf.vhosts.d
    notify: Restart Apache
    template:
      src:  "{{ item }}"
      dest: "{{ apache.serverroot }}/conf.vhosts.d/{{ item | basename | replace('.j2', '') }}"
      mode: "0644"
    with_fileglob: "templates{{ apache.serverroot }}/conf.vhosts.d/*.conf.j2"
  
  - name: make-config | RedHat | Deploy each config file in /etc/httpd/conf.modules.d
    notify: Restart Apache
    template:
      src:  "{{ item }}"
      dest: "{{ apache.serverroot }}/conf.modules.d/{{ item | basename | replace('.j2', '') }}"
      mode: "0644"
    with_fileglob: "templates{{ apache.serverroot }}/conf.modules.d/*.conf.j2"
 when: ansible_os_family == "RedHat" 

- block:
  - name: make-config | Debian | Deploy each config file in /etc/apache2
    notify: Restart Apache
    template:
      src:  "etc/apache2/{{ item }}.j2"
      dest: "{{ apache.configroot }}/{{ item }}"
      mode: "0644"
    with_items:
      - "apache2.conf"
      - "envvars"
      - "magic"
      - "ports.conf"
  
  - name: make-config | Debian | Deploy each config file in /etc/apache2/conf-available
    notify: Restart Apache
    template:
      src:  "{{ item }}"
      dest: "{{ apache.serverroot }}/conf-available/{{ item | basename | replace('.j2', '') }}"
      mode: "0644"
    with_fileglob: "templates{{ apache.serverroot }}/conf-available/*.conf.j2"

  - name: make-config | Debian | Deploy each config file in /etc/apache2/mods-available
    notify: Restart Apache
    template:
      src:  "{{ item }}"
      dest: "{{ apache.serverroot }}/mods-available/{{ item | basename | replace('.j2', '') }}"
      mode: "0644"
    with_fileglob: "templates{{ apache.serverroot }}/mods-available/*.conf.j2"

  - name: make-config | Debian | Deploy each config file in /etc/apache2/sites-available
    notify: Restart Apache
    template:
      src:  "{{ item }}"
      dest: "{{ apache.serverroot }}/sites-available/{{ item | basename | replace('.j2', '') }}"
      mode: "0644"
    with_fileglob: "templates{{ apache.serverroot }}/sites-available/*.conf.j2"

  - name: make-config | Debian | Enable each config file in /etc/apache2/sites-available
    notify: Restart Apache
    file:
      src:   "{{ apache.serverroot }}/sites-available/{{ item | basename | replace('.j2', '') }}"
      dest:  "{{ apache.serverroot }}/sites-enabled/{{ item | basename | replace('.j2', '') }}"
      state: "link"
    with_fileglob: "templates{{ apache.serverroot }}/sites-available/*.conf.j2"

  - name: make-config | Debian | SSL related directories in /etc/apache2 should be exist
    file:
      path:   "{{ apache.serverroot }}/{{ item }}"
      state:  "directory"
      owner:  "root"
      group:  "root"
      mode:   "0755"
    with_items:
      - "certificates"
      - "private-keys"

  - name: make-config | Debian | SSL module should be enabled
    file:
      src:   "{{ apache.serverroot }}/mods-available/ssl.{{ item }}"
      dest:  "{{ apache.serverroot }}/mods-enabled/ssl.{{ item }}"
      state: "link"
    with_items:
      - "load"
      - "conf"

  - name: make-config | Debian | Other modules should be enabled
    file:
      src:   "{{ apache.serverroot }}/mods-available/{{ item }}.load"
      dest:  "{{ apache.serverroot }}/mods-enabled/{{ item }}.load"
      state: "link"
    with_items:
      - "rewrite"
      - "remoteip"
      - "ratelimit"
      - "vhost_alias"
 when: ansible_os_family == "Debian" 

- name: make-config | Deploy log rotation file into /etc/logrotat.d
  template:
    src:  "etc/logrotate.d/{{ apache.name }}.j2"
    dest: "/etc/logrotate.d/{{ apache.name }}"
    mode: "0644"

- name: make-config | Deploy Makefile into /var/log/{{ apache.name }}
  template:
    src:  "var/log/httpd/Makefile.j2"
    dest: "/var/log/{{ apache.name }}/Makefile"
    mode: "0644"

