---
#                         _           __      _       __     ___            _        
#   __ _ _ __   __ _  ___| |__   ___ / /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
#  / _` | '_ \ / _` |/ __| '_ \ / _ \ || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | (_| | |_) | (_| | (__| | | |  __/ || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
#  \__,_| .__/ \__,_|\___|_| |_|\___| || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
#       |_|                          \_\_|        |___/_/                            
# make-config
- name: make-config | Deploy each config file in /etc/httpd/conf
  notify: Restart Apache
  template:
    src:  "etc/httpd/conf/{{ item }}.j2"
    dest: "{{ apache.configroot }}/{{ item }}"
    mode: "0644"
  with_items:
    - "httpd.conf"

- name: make-config | Deploy each config file in /etc/httpd/conf.d
  notify: Restart Apache
  template:
    src:  "{{ item }}"
    dest: "{{ apache.serverroot }}/conf.d/{{ item | basename | replace('.j2', '') }}"
    mode: "0644"
  with_fileglob: "templates{{ apache.serverroot }}/conf.d/*.conf.j2"

- name: make-config | /etc/httpd/conf.vhosts.d should be exist
  file:
    path:   "{{ apache.serverroot }}/conf.vhosts.d"
    state:  "directory"
    owner:  "root"
    group:  "root"
    mode:   "0755"

- name: make-config | /etc/httpd/ssl should be exist
  file:
    path:   "{{ apache.serverroot }}/ssl"
    state:  "directory"
    owner:  "root"
    group:  "root"
    mode:   "0755"

- name: make-config | Deploy each file in /etc/httpd/conf.vhosts.d
  notify: Restart Apache
  template:
    src:  "{{ item }}"
    dest: "{{ apache.serverroot }}/conf.vhosts.d/{{ item | basename | replace('.j2', '') }}"
    mode: "0644"
  with_fileglob: "templates{{ apache.serverroot }}/conf.vhosts.d/*.conf.j2"

- name: make-config | Deploy each config file in /etc/httpd/conf.modules.d
  notify: Restart Apache
  template:
    src:  "{{ item }}"
    dest: "{{ apache.serverroot }}/conf.modules.d/{{ item | basename | replace('.j2', '') }}"
    mode: "0644"
  with_fileglob: "templates{{ apache.serverroot }}/conf.modules.d/*.conf.j2"

