---
#                         _           __      _       __     ___            _        
#   __ _ _ __   __ _  ___| |__   ___ / /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
#  / _` | '_ \ / _` |/ __| '_ \ / _ \ || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | (_| | |_) | (_| | (__| | | |  __/ || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
#  \__,_| .__/ \__,_|\___|_| |_|\___| || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
#       |_|                          \_\_|        |___/_/                            
# php5-module
- block: 
    - name: php5-module | RedHat | PHP5 packages should be installed
      yum:
        name:  "{{ item }}"
        state: "present"
      with_items:
        - "php"
        - "php-common"
        - "php-devel"
        - "php-pear"
        - "php-pdo"
        - "php-cli"
        - "php-gd"
        - "php-mbstring"
        - "php-mcrypt"
        - "php-pgsql"
        - "php-mysqlnd"
        - "php-xml"

    - name: php5-module | RedHat | PHP5 pear packages should be installed
      yum:
        name:  "{{ item }}"
        state: "present"
      with_items:
        - "php-pear-Cache"
        - "php-pear-Cache-Lite"
        - "php-pear-Console-CommandLine"
        - "php-pear-Console-Getargs"
        - "php-pear-Console-ProgressBar"
        - "php-pear-Console-Table"
        - "php-pear-DB"
        - "php-pear-Date"
        - "php-pear-File"
        - "php-pear-File-CSV"
        - "php-pear-File-Util"
        - "php-pear-HTTP-Request"
        - "php-pear-HTTP-Request2"
        - "php-pear-Log"
        - "php-pear-Mail"
        - "php-pear-Mail-Mime"
        - "php-pear-Mail-mimeDecode"
        - "php-pear-Net-Curl"
        - "php-pear-Net-DNS2"
        - "php-pear-Net-FTP"
        - "php-pear-Net-DIME"
        - "php-pear-Net-DNS"
        - "php-pear-Net-IMAP"
        - "php-pear-Net-IPv4"
        - "php-pear-Net-POP3"
        - "php-pear-Net-Ping"
        - "php-pear-Net-SMTP"
        - "php-pear-Net-Socket"
        - "php-pear-Net-Traceroute"
        - "php-pear-Net-URL"
        - "php-pear-Net-URL-Mapper"
        - "php-pear-Net-URL2"
        - "php-pear-Net-UserAgent-Detect"
        - "php-pear-SOAP"
        - "php-pear-XML-Parser"
        - "php-pear-XML-RPC"
        - "php-pear-XML-RPC2"
        - "php-pear-XML-RSS"
        - "php-pear-XML-SVG"
        - "php-pear-XML-Serializer"

    - name: php5-module | RedHat | PHP5 pecl packages should be installed
      yum:
        name:  "{{ item }}"
        state: "present"
      with_items:
        - "php-pecl-http"
        - "php-pecl-imagick"
        - "php-pecl-ncurses"
        - "php-pecl-uuid"

    - name: php5-module | Deploy /etc/php.ini
      notify: Restart Apache
      template:
        src:  "etc/php.ini.j2"
        dest: "/etc/php.ini"
        mode: "0644"

    - name: php5-module | Deploy each config file in /etc/php.d
      notify: Restart Apache
      template:
        src:  "etc/php.d/{{ item }}.j2"
        dest: "/etc/php.d/{{ item }}"
        mode: "0644"
      with_items:
        - "apfd.ini"
        - "curl.ini"
        - "dom.ini"
        - "fileinfo.ini"
        - "gd.ini"
        - "imagick.ini"
        - "json.ini"
        - "json_post.ini"
        - "mbstring.ini"
        - "mcrypt.ini"
        - "mysqlnd.ini"
        - "mysqlnd_mysql.ini"
        - "mysqlnd_mysqli.ini"
        - "ncurses.ini"
        - "pdo.ini"
        - "pdo_mysqlnd.ini"
        - "pdo_pgsql.ini"
        - "pdo_sqlite.ini"
        - "pgsql.ini"
        - "phar.ini"
        - "posix.ini"
        - "propro.ini"
        - "raphf.ini"
        - "sqlite3.ini"
        - "sysvmsg.ini"
        - "sysvsem.ini"
        - "sysvshm.ini"
        - "uuid.ini"
        - "wddx.ini"
        - "xmlreader.ini"
        - "xmlrpc.ini"
        - "xmlwriter.ini"
        - "xsl.ini"
        - "z-http.ini"
        - "zip.ini"

  when: ansible_os_family == "RedHat"
