---
#                         _           __      _       __     ___            _        
#   __ _ _ __   __ _  ___| |__   ___ / /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
#  / _` | '_ \ / _` |/ __| '_ \ / _ \ || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | (_| | |_) | (_| | (__| | | |  __/ || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
#  \__,_| .__/ \__,_|\___|_| |_|\___| || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
#       |_|                          \_\_|        |___/_/                            
# port-config
- block:
  - name: port-config | RedHat | /usr/bin/firewall-cmd exists or not
    register: firewallcmd
    failed_when: firewallcmd.rc < 0
    changed_when: firewallcmd.rc > 1
    command: which firewall-cmd > /dev/null

  - name: port-config | Each HTTP related port should be opened
    when: firewallcmd.rc == 0
    firewalld:
      service:   "{{ item }}"
      state:     "enabled"
      immediate: true
      permanent: true
    with_items: ["http", "443/tcp"]
  when: ansible_os_family == "RedHat" 

- block:
  - name: port-config | Debian | Allow 80 and 443 for Apache
    register: firewallcmd
    ufw:
      rule: "allow"
      name: "{{ item }}"
    with_items:
      - "Apache"
      - "Apache Secure"
  when: ansible_os_family == "Debian" 

- block:
    - name: port-config | Linux | Each HTTP related port should be opened
      when: firewallcmd.rc == 1
      iptables:
        comment:     "open {{ item }}"
        chain:       "INPUT"
        source:      "0.0.0.0"
        destination: "{{ ansible_default_ipv4.address }}"
        destination_port: "{{ item }}"
        protocol:    "tcp"
        jump:        "ACCEPT"
      with_items:
        - "80"
        - "443"
  when: ansible_system == "Linux"
    
