---
#                         _           __      _       __     ___            _        
#   __ _ _ __   __ _  ___| |__   ___ / /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
#  / _` | '_ \ / _` |/ __| '_ \ / _ \ || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | (_| | |_) | (_| | (__| | | |  __/ || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
#  \__,_| .__/ \__,_|\___|_| |_|\___| || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
#       |_|                          \_\_|        |___/_/                            
# port-config
- name: port-config | HTTP(80) port should be opened
  firewalld:
    service:   "http"
    state:     "enabled"
    immediate: true
    permanent: true

- name: port-config | HTTPS(443) port should be opened
  firewalld:
    port:      "443/tcp"
    state:     "enabled"
    immediate: true
    permanent: true

